// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 6.30.2

#ifndef messages_2eproto_2epb_2eh
#define messages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_messages_2eproto;
}  // extern "C"
namespace GameMsg {
enum TestExa_Person_PhoneType : int;
extern const uint32_t TestExa_Person_PhoneType_internal_data_[];
class TestExa;
struct TestExaDefaultTypeInternal;
extern TestExaDefaultTypeInternal _TestExa_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestExa_class_data_;
class TestExa_AddressBook;
struct TestExa_AddressBookDefaultTypeInternal;
extern TestExa_AddressBookDefaultTypeInternal _TestExa_AddressBook_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestExa_AddressBook_class_data_;
class TestExa_Person;
struct TestExa_PersonDefaultTypeInternal;
extern TestExa_PersonDefaultTypeInternal _TestExa_Person_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestExa_Person_class_data_;
class TestExa_Person_PhoneNumber;
struct TestExa_Person_PhoneNumberDefaultTypeInternal;
extern TestExa_Person_PhoneNumberDefaultTypeInternal _TestExa_Person_PhoneNumber_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestExa_Person_PhoneNumber_class_data_;
}  // namespace GameMsg
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::GameMsg::TestExa_Person_PhoneType_internal_data_>
    internal::EnumTraitsImpl::value<::GameMsg::TestExa_Person_PhoneType>;
}  // namespace protobuf
}  // namespace google

namespace GameMsg {
enum TestExa_Person_PhoneType : int {
  TestExa_Person_PhoneType_MOBILE = 0,
  TestExa_Person_PhoneType_HOME = 1,
  TestExa_Person_PhoneType_WORK = 2,
  TestExa_Person_PhoneType_TestExa_Person_PhoneType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  TestExa_Person_PhoneType_TestExa_Person_PhoneType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t TestExa_Person_PhoneType_internal_data_[];
inline constexpr TestExa_Person_PhoneType TestExa_Person_PhoneType_PhoneType_MIN =
    static_cast<TestExa_Person_PhoneType>(0);
inline constexpr TestExa_Person_PhoneType TestExa_Person_PhoneType_PhoneType_MAX =
    static_cast<TestExa_Person_PhoneType>(2);
inline bool TestExa_Person_PhoneType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int TestExa_Person_PhoneType_PhoneType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TestExa_Person_PhoneType_descriptor();
template <typename T>
const std::string& TestExa_Person_PhoneType_Name(T value) {
  static_assert(std::is_same<T, TestExa_Person_PhoneType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PhoneType_Name().");
  return TestExa_Person_PhoneType_Name(static_cast<TestExa_Person_PhoneType>(value));
}
template <>
inline const std::string& TestExa_Person_PhoneType_Name(TestExa_Person_PhoneType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TestExa_Person_PhoneType_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool TestExa_Person_PhoneType_Parse(
    absl::string_view name, TestExa_Person_PhoneType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<TestExa_Person_PhoneType>(TestExa_Person_PhoneType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class TestExa_Person_PhoneNumber final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameMsg.TestExa.Person.PhoneNumber) */ {
 public:
  inline TestExa_Person_PhoneNumber() : TestExa_Person_PhoneNumber(nullptr) {}
  ~TestExa_Person_PhoneNumber() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TestExa_Person_PhoneNumber* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TestExa_Person_PhoneNumber));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestExa_Person_PhoneNumber(::google::protobuf::internal::ConstantInitialized);

  inline TestExa_Person_PhoneNumber(const TestExa_Person_PhoneNumber& from) : TestExa_Person_PhoneNumber(nullptr, from) {}
  inline TestExa_Person_PhoneNumber(TestExa_Person_PhoneNumber&& from) noexcept
      : TestExa_Person_PhoneNumber(nullptr, std::move(from)) {}
  inline TestExa_Person_PhoneNumber& operator=(const TestExa_Person_PhoneNumber& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestExa_Person_PhoneNumber& operator=(TestExa_Person_PhoneNumber&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestExa_Person_PhoneNumber& default_instance() {
    return *reinterpret_cast<const TestExa_Person_PhoneNumber*>(
        &_TestExa_Person_PhoneNumber_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TestExa_Person_PhoneNumber& a, TestExa_Person_PhoneNumber& b) { a.Swap(&b); }
  inline void Swap(TestExa_Person_PhoneNumber* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestExa_Person_PhoneNumber* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestExa_Person_PhoneNumber* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TestExa_Person_PhoneNumber>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestExa_Person_PhoneNumber& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestExa_Person_PhoneNumber& from) { TestExa_Person_PhoneNumber::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TestExa_Person_PhoneNumber* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameMsg.TestExa.Person.PhoneNumber"; }

 protected:
  explicit TestExa_Person_PhoneNumber(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TestExa_Person_PhoneNumber(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestExa_Person_PhoneNumber& from);
  TestExa_Person_PhoneNumber(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TestExa_Person_PhoneNumber&& from) noexcept
      : TestExa_Person_PhoneNumber(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string number = 1;
  void clear_number() ;
  const std::string& number() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_number(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_number();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_number();
  void set_allocated_number(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_number() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_number(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_number();

  public:
  // optional .GameMsg.TestExa.Person.PhoneType type = 2;
  bool has_type() const;
  void clear_type() ;
  ::GameMsg::TestExa_Person_PhoneType type() const;
  void set_type(::GameMsg::TestExa_Person_PhoneType value);

  private:
  ::GameMsg::TestExa_Person_PhoneType _internal_type() const;
  void _internal_set_type(::GameMsg::TestExa_Person_PhoneType value);

  public:
  // @@protoc_insertion_point(class_scope:GameMsg.TestExa.Person.PhoneNumber)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 49,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TestExa_Person_PhoneNumber& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr number_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TestExa_Person_PhoneNumber_class_data_;
// -------------------------------------------------------------------

class TestExa final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:GameMsg.TestExa) */ {
 public:
  inline TestExa() : TestExa(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TestExa* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TestExa));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestExa(::google::protobuf::internal::ConstantInitialized);

  inline TestExa(const TestExa& from) : TestExa(nullptr, from) {}
  inline TestExa(TestExa&& from) noexcept
      : TestExa(nullptr, std::move(from)) {}
  inline TestExa& operator=(const TestExa& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestExa& operator=(TestExa&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestExa& default_instance() {
    return *reinterpret_cast<const TestExa*>(
        &_TestExa_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(TestExa& a, TestExa& b) { a.Swap(&b); }
  inline void Swap(TestExa* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestExa* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestExa* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<TestExa>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const TestExa& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const TestExa& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameMsg.TestExa"; }

 protected:
  explicit TestExa(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TestExa(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestExa& from);
  TestExa(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TestExa&& from) noexcept
      : TestExa(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Person = TestExa_Person;
  using AddressBook = TestExa_AddressBook;

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:GameMsg.TestExa)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TestExa& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TestExa_class_data_;
// -------------------------------------------------------------------

class TestExa_Person final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameMsg.TestExa.Person) */ {
 public:
  inline TestExa_Person() : TestExa_Person(nullptr) {}
  ~TestExa_Person() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TestExa_Person* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TestExa_Person));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestExa_Person(::google::protobuf::internal::ConstantInitialized);

  inline TestExa_Person(const TestExa_Person& from) : TestExa_Person(nullptr, from) {}
  inline TestExa_Person(TestExa_Person&& from) noexcept
      : TestExa_Person(nullptr, std::move(from)) {}
  inline TestExa_Person& operator=(const TestExa_Person& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestExa_Person& operator=(TestExa_Person&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestExa_Person& default_instance() {
    return *reinterpret_cast<const TestExa_Person*>(
        &_TestExa_Person_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TestExa_Person& a, TestExa_Person& b) { a.Swap(&b); }
  inline void Swap(TestExa_Person* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestExa_Person* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestExa_Person* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TestExa_Person>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestExa_Person& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestExa_Person& from) { TestExa_Person::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TestExa_Person* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameMsg.TestExa.Person"; }

 protected:
  explicit TestExa_Person(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TestExa_Person(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestExa_Person& from);
  TestExa_Person(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TestExa_Person&& from) noexcept
      : TestExa_Person(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using PhoneNumber = TestExa_Person_PhoneNumber;
  using PhoneType = TestExa_Person_PhoneType;
  static constexpr PhoneType MOBILE = TestExa_Person_PhoneType_MOBILE;
  static constexpr PhoneType HOME = TestExa_Person_PhoneType_HOME;
  static constexpr PhoneType WORK = TestExa_Person_PhoneType_WORK;
  static inline bool PhoneType_IsValid(int value) {
    return TestExa_Person_PhoneType_IsValid(value);
  }
  static constexpr PhoneType PhoneType_MIN = TestExa_Person_PhoneType_PhoneType_MIN;
  static constexpr PhoneType PhoneType_MAX = TestExa_Person_PhoneType_PhoneType_MAX;
  static constexpr int PhoneType_ARRAYSIZE = TestExa_Person_PhoneType_PhoneType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PhoneType_descriptor() {
    return TestExa_Person_PhoneType_descriptor();
  }
  template <typename T>
  static inline const std::string& PhoneType_Name(T value) {
    return TestExa_Person_PhoneType_Name(value);
  }
  static inline bool PhoneType_Parse(
      absl::string_view name, PhoneType* PROTOBUF_NONNULL value) {
    return TestExa_Person_PhoneType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kPhoneFieldNumber = 4,
    kNameFieldNumber = 1,
    kEmailFieldNumber = 3,
    kIdFieldNumber = 2,
  };
  // repeated .GameMsg.TestExa.Person.PhoneNumber phone = 4;
  int phone_size() const;
  private:
  int _internal_phone_size() const;

  public:
  void clear_phone() ;
  ::GameMsg::TestExa_Person_PhoneNumber* PROTOBUF_NONNULL mutable_phone(int index);
  ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person_PhoneNumber>* PROTOBUF_NONNULL mutable_phone();

  private:
  const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person_PhoneNumber>& _internal_phone() const;
  ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person_PhoneNumber>* PROTOBUF_NONNULL _internal_mutable_phone();
  public:
  const ::GameMsg::TestExa_Person_PhoneNumber& phone(int index) const;
  ::GameMsg::TestExa_Person_PhoneNumber* PROTOBUF_NONNULL add_phone();
  const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person_PhoneNumber>& phone() const;
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // optional string email = 3;
  bool has_email() const;
  void clear_email() ;
  const std::string& email() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_email();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_email();
  void set_allocated_email(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_email() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_email();

  public:
  // int32 id = 2;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameMsg.TestExa.Person)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 40,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TestExa_Person& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::GameMsg::TestExa_Person_PhoneNumber > phone_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr email_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TestExa_Person_class_data_;
// -------------------------------------------------------------------

class TestExa_AddressBook final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameMsg.TestExa.AddressBook) */ {
 public:
  inline TestExa_AddressBook() : TestExa_AddressBook(nullptr) {}
  ~TestExa_AddressBook() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TestExa_AddressBook* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TestExa_AddressBook));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestExa_AddressBook(::google::protobuf::internal::ConstantInitialized);

  inline TestExa_AddressBook(const TestExa_AddressBook& from) : TestExa_AddressBook(nullptr, from) {}
  inline TestExa_AddressBook(TestExa_AddressBook&& from) noexcept
      : TestExa_AddressBook(nullptr, std::move(from)) {}
  inline TestExa_AddressBook& operator=(const TestExa_AddressBook& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestExa_AddressBook& operator=(TestExa_AddressBook&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestExa_AddressBook& default_instance() {
    return *reinterpret_cast<const TestExa_AddressBook*>(
        &_TestExa_AddressBook_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(TestExa_AddressBook& a, TestExa_AddressBook& b) { a.Swap(&b); }
  inline void Swap(TestExa_AddressBook* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestExa_AddressBook* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestExa_AddressBook* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TestExa_AddressBook>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestExa_AddressBook& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestExa_AddressBook& from) { TestExa_AddressBook::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TestExa_AddressBook* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameMsg.TestExa.AddressBook"; }

 protected:
  explicit TestExa_AddressBook(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TestExa_AddressBook(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestExa_AddressBook& from);
  TestExa_AddressBook(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TestExa_AddressBook&& from) noexcept
      : TestExa_AddressBook(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPersonFieldNumber = 1,
    kPerson1FieldNumber = 2,
  };
  // repeated .GameMsg.TestExa.Person person = 1;
  int person_size() const;
  private:
  int _internal_person_size() const;

  public:
  void clear_person() ;
  ::GameMsg::TestExa_Person* PROTOBUF_NONNULL mutable_person(int index);
  ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>* PROTOBUF_NONNULL mutable_person();

  private:
  const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>& _internal_person() const;
  ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>* PROTOBUF_NONNULL _internal_mutable_person();
  public:
  const ::GameMsg::TestExa_Person& person(int index) const;
  ::GameMsg::TestExa_Person* PROTOBUF_NONNULL add_person();
  const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>& person() const;
  // repeated .GameMsg.TestExa.Person person1 = 2;
  int person1_size() const;
  private:
  int _internal_person1_size() const;

  public:
  void clear_person1() ;
  ::GameMsg::TestExa_Person* PROTOBUF_NONNULL mutable_person1(int index);
  ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>* PROTOBUF_NONNULL mutable_person1();

  private:
  const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>& _internal_person1() const;
  ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>* PROTOBUF_NONNULL _internal_mutable_person1();
  public:
  const ::GameMsg::TestExa_Person& person1(int index) const;
  ::GameMsg::TestExa_Person* PROTOBUF_NONNULL add_person1();
  const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>& person1() const;
  // @@protoc_insertion_point(class_scope:GameMsg.TestExa.AddressBook)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TestExa_AddressBook& from_msg);
    ::google::protobuf::RepeatedPtrField< ::GameMsg::TestExa_Person > person_;
    ::google::protobuf::RepeatedPtrField< ::GameMsg::TestExa_Person > person1_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TestExa_AddressBook_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TestExa_Person_PhoneNumber

// string number = 1;
inline void TestExa_Person_PhoneNumber::clear_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TestExa_Person_PhoneNumber::number() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameMsg.TestExa.Person.PhoneNumber.number)
  return _internal_number();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TestExa_Person_PhoneNumber::set_number(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.number_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameMsg.TestExa.Person.PhoneNumber.number)
}
inline std::string* PROTOBUF_NONNULL TestExa_Person_PhoneNumber::mutable_number()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_number();
  // @@protoc_insertion_point(field_mutable:GameMsg.TestExa.Person.PhoneNumber.number)
  return _s;
}
inline const std::string& TestExa_Person_PhoneNumber::_internal_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.number_.Get();
}
inline void TestExa_Person_PhoneNumber::_internal_set_number(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.number_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL TestExa_Person_PhoneNumber::_internal_mutable_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.number_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE TestExa_Person_PhoneNumber::release_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameMsg.TestExa.Person.PhoneNumber.number)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.number_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.number_.Set("", GetArena());
  }
  return released;
}
inline void TestExa_Person_PhoneNumber::set_allocated_number(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.number_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.number_.IsDefault()) {
    _impl_.number_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameMsg.TestExa.Person.PhoneNumber.number)
}

// optional .GameMsg.TestExa.Person.PhoneType type = 2;
inline bool TestExa_Person_PhoneNumber::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void TestExa_Person_PhoneNumber::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::GameMsg::TestExa_Person_PhoneType TestExa_Person_PhoneNumber::type() const {
  // @@protoc_insertion_point(field_get:GameMsg.TestExa.Person.PhoneNumber.type)
  return _internal_type();
}
inline void TestExa_Person_PhoneNumber::set_type(::GameMsg::TestExa_Person_PhoneType value) {
  _internal_set_type(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:GameMsg.TestExa.Person.PhoneNumber.type)
}
inline ::GameMsg::TestExa_Person_PhoneType TestExa_Person_PhoneNumber::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::GameMsg::TestExa_Person_PhoneType>(_impl_.type_);
}
inline void TestExa_Person_PhoneNumber::_internal_set_type(::GameMsg::TestExa_Person_PhoneType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// -------------------------------------------------------------------

// TestExa_Person

// string name = 1;
inline void TestExa_Person::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TestExa_Person::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameMsg.TestExa.Person.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TestExa_Person::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameMsg.TestExa.Person.name)
}
inline std::string* PROTOBUF_NONNULL TestExa_Person::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:GameMsg.TestExa.Person.name)
  return _s;
}
inline const std::string& TestExa_Person::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void TestExa_Person::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL TestExa_Person::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE TestExa_Person::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameMsg.TestExa.Person.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void TestExa_Person::set_allocated_name(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameMsg.TestExa.Person.name)
}

// int32 id = 2;
inline void TestExa_Person::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t TestExa_Person::id() const {
  // @@protoc_insertion_point(field_get:GameMsg.TestExa.Person.id)
  return _internal_id();
}
inline void TestExa_Person::set_id(::int32_t value) {
  _internal_set_id(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:GameMsg.TestExa.Person.id)
}
inline ::int32_t TestExa_Person::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void TestExa_Person::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// optional string email = 3;
inline bool TestExa_Person::has_email() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void TestExa_Person::clear_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& TestExa_Person::email() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameMsg.TestExa.Person.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TestExa_Person::set_email(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameMsg.TestExa.Person.email)
}
inline std::string* PROTOBUF_NONNULL TestExa_Person::mutable_email()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:GameMsg.TestExa.Person.email)
  return _s;
}
inline const std::string& TestExa_Person::_internal_email() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.email_.Get();
}
inline void TestExa_Person::_internal_set_email(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.email_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL TestExa_Person::_internal_mutable_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.email_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE TestExa_Person::release_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameMsg.TestExa.Person.email)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.email_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.email_.Set("", GetArena());
  }
  return released;
}
inline void TestExa_Person::set_allocated_email(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.email_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameMsg.TestExa.Person.email)
}

// repeated .GameMsg.TestExa.Person.PhoneNumber phone = 4;
inline int TestExa_Person::_internal_phone_size() const {
  return _internal_phone().size();
}
inline int TestExa_Person::phone_size() const {
  return _internal_phone_size();
}
inline void TestExa_Person::clear_phone() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.phone_.Clear();
}
inline ::GameMsg::TestExa_Person_PhoneNumber* PROTOBUF_NONNULL TestExa_Person::mutable_phone(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:GameMsg.TestExa.Person.phone)
  return _internal_mutable_phone()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person_PhoneNumber>* PROTOBUF_NONNULL TestExa_Person::mutable_phone()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:GameMsg.TestExa.Person.phone)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_phone();
}
inline const ::GameMsg::TestExa_Person_PhoneNumber& TestExa_Person::phone(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameMsg.TestExa.Person.phone)
  return _internal_phone().Get(index);
}
inline ::GameMsg::TestExa_Person_PhoneNumber* PROTOBUF_NONNULL TestExa_Person::add_phone()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::GameMsg::TestExa_Person_PhoneNumber* _add = _internal_mutable_phone()->Add();
  // @@protoc_insertion_point(field_add:GameMsg.TestExa.Person.phone)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person_PhoneNumber>& TestExa_Person::phone() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:GameMsg.TestExa.Person.phone)
  return _internal_phone();
}
inline const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person_PhoneNumber>&
TestExa_Person::_internal_phone() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.phone_;
}
inline ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person_PhoneNumber>* PROTOBUF_NONNULL
TestExa_Person::_internal_mutable_phone() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.phone_;
}

// -------------------------------------------------------------------

// TestExa_AddressBook

// repeated .GameMsg.TestExa.Person person = 1;
inline int TestExa_AddressBook::_internal_person_size() const {
  return _internal_person().size();
}
inline int TestExa_AddressBook::person_size() const {
  return _internal_person_size();
}
inline void TestExa_AddressBook::clear_person() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.person_.Clear();
}
inline ::GameMsg::TestExa_Person* PROTOBUF_NONNULL TestExa_AddressBook::mutable_person(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:GameMsg.TestExa.AddressBook.person)
  return _internal_mutable_person()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>* PROTOBUF_NONNULL TestExa_AddressBook::mutable_person()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:GameMsg.TestExa.AddressBook.person)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_person();
}
inline const ::GameMsg::TestExa_Person& TestExa_AddressBook::person(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameMsg.TestExa.AddressBook.person)
  return _internal_person().Get(index);
}
inline ::GameMsg::TestExa_Person* PROTOBUF_NONNULL TestExa_AddressBook::add_person()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::GameMsg::TestExa_Person* _add = _internal_mutable_person()->Add();
  // @@protoc_insertion_point(field_add:GameMsg.TestExa.AddressBook.person)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>& TestExa_AddressBook::person() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:GameMsg.TestExa.AddressBook.person)
  return _internal_person();
}
inline const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>&
TestExa_AddressBook::_internal_person() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.person_;
}
inline ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>* PROTOBUF_NONNULL
TestExa_AddressBook::_internal_mutable_person() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.person_;
}

// repeated .GameMsg.TestExa.Person person1 = 2;
inline int TestExa_AddressBook::_internal_person1_size() const {
  return _internal_person1().size();
}
inline int TestExa_AddressBook::person1_size() const {
  return _internal_person1_size();
}
inline void TestExa_AddressBook::clear_person1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.person1_.Clear();
}
inline ::GameMsg::TestExa_Person* PROTOBUF_NONNULL TestExa_AddressBook::mutable_person1(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:GameMsg.TestExa.AddressBook.person1)
  return _internal_mutable_person1()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>* PROTOBUF_NONNULL TestExa_AddressBook::mutable_person1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:GameMsg.TestExa.AddressBook.person1)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_person1();
}
inline const ::GameMsg::TestExa_Person& TestExa_AddressBook::person1(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameMsg.TestExa.AddressBook.person1)
  return _internal_person1().Get(index);
}
inline ::GameMsg::TestExa_Person* PROTOBUF_NONNULL TestExa_AddressBook::add_person1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::GameMsg::TestExa_Person* _add = _internal_mutable_person1()->Add();
  // @@protoc_insertion_point(field_add:GameMsg.TestExa.AddressBook.person1)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>& TestExa_AddressBook::person1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:GameMsg.TestExa.AddressBook.person1)
  return _internal_person1();
}
inline const ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>&
TestExa_AddressBook::_internal_person1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.person1_;
}
inline ::google::protobuf::RepeatedPtrField<::GameMsg::TestExa_Person>* PROTOBUF_NONNULL
TestExa_AddressBook::_internal_mutable_person1() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.person1_;
}

// -------------------------------------------------------------------

// TestExa

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace GameMsg


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::GameMsg::TestExa_Person_PhoneType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::GameMsg::TestExa_Person_PhoneType>() {
  return ::GameMsg::TestExa_Person_PhoneType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // messages_2eproto_2epb_2eh
