// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 5.29.3

#include "messages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GameMsg {

inline constexpr TestExa_Person_PhoneNumber::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        number_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::GameMsg::TestExa_Person_PhoneType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR TestExa_Person_PhoneNumber::TestExa_Person_PhoneNumber(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TestExa_Person_PhoneNumberDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestExa_Person_PhoneNumberDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestExa_Person_PhoneNumberDefaultTypeInternal() {}
  union {
    TestExa_Person_PhoneNumber _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestExa_Person_PhoneNumberDefaultTypeInternal _TestExa_Person_PhoneNumber_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR TestExa::TestExa(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct TestExaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestExaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestExaDefaultTypeInternal() {}
  union {
    TestExa _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestExaDefaultTypeInternal _TestExa_default_instance_;

inline constexpr TestExa_Person::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        phone_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TestExa_Person::TestExa_Person(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TestExa_PersonDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestExa_PersonDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestExa_PersonDefaultTypeInternal() {}
  union {
    TestExa_Person _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestExa_PersonDefaultTypeInternal _TestExa_Person_default_instance_;

inline constexpr TestExa_AddressBook::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : person_{},
        person1_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TestExa_AddressBook::TestExa_AddressBook(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TestExa_AddressBookDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestExa_AddressBookDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestExa_AddressBookDefaultTypeInternal() {}
  union {
    TestExa_AddressBook _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestExa_AddressBookDefaultTypeInternal _TestExa_AddressBook_default_instance_;
}  // namespace GameMsg
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_messages_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_messages_2eproto = nullptr;
const ::uint32_t
    TableStruct_messages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person_PhoneNumber, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person_PhoneNumber, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person_PhoneNumber, _impl_.number_),
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person_PhoneNumber, _impl_.type_),
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_Person, _impl_.phone_),
        ~0u,
        ~0u,
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_AddressBook, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_AddressBook, _impl_.person_),
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa_AddressBook, _impl_.person1_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GameMsg::TestExa, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::GameMsg::TestExa_Person_PhoneNumber)},
        {12, 24, -1, sizeof(::GameMsg::TestExa_Person)},
        {28, -1, -1, sizeof(::GameMsg::TestExa_AddressBook)},
        {38, -1, -1, sizeof(::GameMsg::TestExa)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::GameMsg::_TestExa_Person_PhoneNumber_default_instance_._instance,
    &::GameMsg::_TestExa_Person_default_instance_._instance,
    &::GameMsg::_TestExa_AddressBook_default_instance_._instance,
    &::GameMsg::_TestExa_default_instance_._instance,
};
const char descriptor_table_protodef_messages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016messages.proto\022\007GameMsg\"\355\002\n\007TestExa\032\377\001"
    "\n\006Person\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\022\n\005em"
    "ail\030\003 \001(\tH\000\210\001\001\0222\n\005phone\030\004 \003(\0132#.GameMsg."
    "TestExa.Person.PhoneNumber\032\\\n\013PhoneNumbe"
    "r\022\016\n\006number\030\001 \001(\t\0224\n\004type\030\002 \001(\0162!.GameMs"
    "g.TestExa.Person.PhoneTypeH\000\210\001\001B\007\n\005_type"
    "\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004W"
    "ORK\020\002B\010\n\006_email\032`\n\013AddressBook\022\'\n\006person"
    "\030\001 \003(\0132\027.GameMsg.TestExa.Person\022(\n\007perso"
    "n1\030\002 \003(\0132\027.GameMsg.TestExa.Personb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_messages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_messages_2eproto = {
    false,
    false,
    401,
    descriptor_table_protodef_messages_2eproto,
    "messages.proto",
    &descriptor_table_messages_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_messages_2eproto::offsets,
    file_level_enum_descriptors_messages_2eproto,
    file_level_service_descriptors_messages_2eproto,
};
namespace GameMsg {
const ::google::protobuf::EnumDescriptor* TestExa_Person_PhoneType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TestExa_Person_PhoneType_internal_data_[] = {
    196608u, 0u, };
bool TestExa_Person_PhoneType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr TestExa_Person_PhoneType TestExa_Person::MOBILE;
constexpr TestExa_Person_PhoneType TestExa_Person::HOME;
constexpr TestExa_Person_PhoneType TestExa_Person::WORK;
constexpr TestExa_Person_PhoneType TestExa_Person::PhoneType_MIN;
constexpr TestExa_Person_PhoneType TestExa_Person::PhoneType_MAX;
constexpr int TestExa_Person::PhoneType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class TestExa_Person_PhoneNumber::_Internal {
 public:
  using HasBits =
      decltype(std::declval<TestExa_Person_PhoneNumber>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TestExa_Person_PhoneNumber, _impl_._has_bits_);
};

TestExa_Person_PhoneNumber::TestExa_Person_PhoneNumber(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameMsg.TestExa.Person.PhoneNumber)
}
inline PROTOBUF_NDEBUG_INLINE TestExa_Person_PhoneNumber::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameMsg::TestExa_Person_PhoneNumber& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        number_(arena, from.number_) {}

TestExa_Person_PhoneNumber::TestExa_Person_PhoneNumber(
    ::google::protobuf::Arena* arena,
    const TestExa_Person_PhoneNumber& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TestExa_Person_PhoneNumber* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:GameMsg.TestExa.Person.PhoneNumber)
}
inline PROTOBUF_NDEBUG_INLINE TestExa_Person_PhoneNumber::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        number_(arena) {}

inline void TestExa_Person_PhoneNumber::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
TestExa_Person_PhoneNumber::~TestExa_Person_PhoneNumber() {
  // @@protoc_insertion_point(destructor:GameMsg.TestExa.Person.PhoneNumber)
  SharedDtor(*this);
}
inline void TestExa_Person_PhoneNumber::SharedDtor(MessageLite& self) {
  TestExa_Person_PhoneNumber& this_ = static_cast<TestExa_Person_PhoneNumber&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.number_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TestExa_Person_PhoneNumber::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TestExa_Person_PhoneNumber(arena);
}
constexpr auto TestExa_Person_PhoneNumber::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TestExa_Person_PhoneNumber),
                                            alignof(TestExa_Person_PhoneNumber));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TestExa_Person_PhoneNumber::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TestExa_Person_PhoneNumber_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TestExa_Person_PhoneNumber::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TestExa_Person_PhoneNumber>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TestExa_Person_PhoneNumber::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TestExa_Person_PhoneNumber>(), &TestExa_Person_PhoneNumber::ByteSizeLong,
            &TestExa_Person_PhoneNumber::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TestExa_Person_PhoneNumber, _impl_._cached_size_),
        false,
    },
    &TestExa_Person_PhoneNumber::kDescriptorMethods,
    &descriptor_table_messages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TestExa_Person_PhoneNumber::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 49, 2> TestExa_Person_PhoneNumber::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TestExa_Person_PhoneNumber, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameMsg::TestExa_Person_PhoneNumber>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .GameMsg.TestExa.Person.PhoneType type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestExa_Person_PhoneNumber, _impl_.type_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(TestExa_Person_PhoneNumber, _impl_.type_)}},
    // string number = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TestExa_Person_PhoneNumber, _impl_.number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string number = 1;
    {PROTOBUF_FIELD_OFFSET(TestExa_Person_PhoneNumber, _impl_.number_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .GameMsg.TestExa.Person.PhoneType type = 2;
    {PROTOBUF_FIELD_OFFSET(TestExa_Person_PhoneNumber, _impl_.type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\42\6\0\0\0\0\0\0"
    "GameMsg.TestExa.Person.PhoneNumber"
    "number"
  }},
};

PROTOBUF_NOINLINE void TestExa_Person_PhoneNumber::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMsg.TestExa.Person.PhoneNumber)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.number_.ClearToEmpty();
  _impl_.type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TestExa_Person_PhoneNumber::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TestExa_Person_PhoneNumber& this_ = static_cast<const TestExa_Person_PhoneNumber&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TestExa_Person_PhoneNumber::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TestExa_Person_PhoneNumber& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameMsg.TestExa.Person.PhoneNumber)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string number = 1;
          if (!this_._internal_number().empty()) {
            const std::string& _s = this_._internal_number();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameMsg.TestExa.Person.PhoneNumber.number");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .GameMsg.TestExa.Person.PhoneType type = 2;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_type(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameMsg.TestExa.Person.PhoneNumber)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TestExa_Person_PhoneNumber::ByteSizeLong(const MessageLite& base) {
          const TestExa_Person_PhoneNumber& this_ = static_cast<const TestExa_Person_PhoneNumber&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TestExa_Person_PhoneNumber::ByteSizeLong() const {
          const TestExa_Person_PhoneNumber& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameMsg.TestExa.Person.PhoneNumber)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string number = 1;
            if (!this_._internal_number().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_number());
            }
          }
           {
            // optional .GameMsg.TestExa.Person.PhoneType type = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TestExa_Person_PhoneNumber::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TestExa_Person_PhoneNumber*>(&to_msg);
  auto& from = static_cast<const TestExa_Person_PhoneNumber&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMsg.TestExa.Person.PhoneNumber)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_number().empty()) {
    _this->_internal_set_number(from._internal_number());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TestExa_Person_PhoneNumber::CopyFrom(const TestExa_Person_PhoneNumber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMsg.TestExa.Person.PhoneNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestExa_Person_PhoneNumber::InternalSwap(TestExa_Person_PhoneNumber* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.number_, &other->_impl_.number_, arena);
  swap(_impl_.type_, other->_impl_.type_);
}

::google::protobuf::Metadata TestExa_Person_PhoneNumber::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TestExa_Person::_Internal {
 public:
  using HasBits =
      decltype(std::declval<TestExa_Person>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_._has_bits_);
};

TestExa_Person::TestExa_Person(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameMsg.TestExa.Person)
}
inline PROTOBUF_NDEBUG_INLINE TestExa_Person::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameMsg::TestExa_Person& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        phone_{visibility, arena, from.phone_},
        name_(arena, from.name_),
        email_(arena, from.email_) {}

TestExa_Person::TestExa_Person(
    ::google::protobuf::Arena* arena,
    const TestExa_Person& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TestExa_Person* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:GameMsg.TestExa.Person)
}
inline PROTOBUF_NDEBUG_INLINE TestExa_Person::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        phone_{visibility, arena},
        name_(arena),
        email_(arena) {}

inline void TestExa_Person::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
TestExa_Person::~TestExa_Person() {
  // @@protoc_insertion_point(destructor:GameMsg.TestExa.Person)
  SharedDtor(*this);
}
inline void TestExa_Person::SharedDtor(MessageLite& self) {
  TestExa_Person& this_ = static_cast<TestExa_Person&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.email_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TestExa_Person::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TestExa_Person(arena);
}
constexpr auto TestExa_Person::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.phone_) +
          decltype(TestExa_Person::_impl_.phone_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(TestExa_Person), alignof(TestExa_Person), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TestExa_Person::PlacementNew_,
                                 sizeof(TestExa_Person),
                                 alignof(TestExa_Person));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TestExa_Person::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TestExa_Person_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TestExa_Person::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TestExa_Person>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TestExa_Person::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TestExa_Person>(), &TestExa_Person::ByteSizeLong,
            &TestExa_Person::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_._cached_size_),
        false,
    },
    &TestExa_Person::kDescriptorMethods,
    &descriptor_table_messages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TestExa_Person::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 40, 2> TestExa_Person::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameMsg::TestExa_Person>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .GameMsg.TestExa.Person.PhoneNumber phone = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.phone_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.name_)}},
    // int32 id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestExa_Person, _impl_.id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.id_)}},
    // optional string email = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.email_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 id = 2;
    {PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // optional string email = 3;
    {PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.email_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .GameMsg.TestExa.Person.PhoneNumber phone = 4;
    {PROTOBUF_FIELD_OFFSET(TestExa_Person, _impl_.phone_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GameMsg::TestExa_Person_PhoneNumber>()},
  }}, {{
    "\26\4\0\5\0\0\0\0"
    "GameMsg.TestExa.Person"
    "name"
    "email"
  }},
};

PROTOBUF_NOINLINE void TestExa_Person::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMsg.TestExa.Person)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.phone_.Clear();
  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.email_.ClearNonDefaultToEmpty();
  }
  _impl_.id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TestExa_Person::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TestExa_Person& this_ = static_cast<const TestExa_Person&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TestExa_Person::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TestExa_Person& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameMsg.TestExa.Person)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameMsg.TestExa.Person.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 id = 2;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_id(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string email = 3;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_email();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameMsg.TestExa.Person.email");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // repeated .GameMsg.TestExa.Person.PhoneNumber phone = 4;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_phone_size());
               i < n; i++) {
            const auto& repfield = this_._internal_phone().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    4, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameMsg.TestExa.Person)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TestExa_Person::ByteSizeLong(const MessageLite& base) {
          const TestExa_Person& this_ = static_cast<const TestExa_Person&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TestExa_Person::ByteSizeLong() const {
          const TestExa_Person& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameMsg.TestExa.Person)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .GameMsg.TestExa.Person.PhoneNumber phone = 4;
            {
              total_size += 1UL * this_._internal_phone_size();
              for (const auto& msg : this_._internal_phone()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
           {
            // optional string email = 3;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_email());
            }
          }
           {
            // int32 id = 2;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TestExa_Person::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TestExa_Person*>(&to_msg);
  auto& from = static_cast<const TestExa_Person&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMsg.TestExa.Person)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_phone()->MergeFrom(
      from._internal_phone());
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_internal_set_email(from._internal_email());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TestExa_Person::CopyFrom(const TestExa_Person& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMsg.TestExa.Person)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestExa_Person::InternalSwap(TestExa_Person* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.phone_.InternalSwap(&other->_impl_.phone_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata TestExa_Person::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TestExa_AddressBook::_Internal {
 public:
};

TestExa_AddressBook::TestExa_AddressBook(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameMsg.TestExa.AddressBook)
}
inline PROTOBUF_NDEBUG_INLINE TestExa_AddressBook::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameMsg::TestExa_AddressBook& from_msg)
      : person_{visibility, arena, from.person_},
        person1_{visibility, arena, from.person1_},
        _cached_size_{0} {}

TestExa_AddressBook::TestExa_AddressBook(
    ::google::protobuf::Arena* arena,
    const TestExa_AddressBook& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TestExa_AddressBook* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GameMsg.TestExa.AddressBook)
}
inline PROTOBUF_NDEBUG_INLINE TestExa_AddressBook::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : person_{visibility, arena},
        person1_{visibility, arena},
        _cached_size_{0} {}

inline void TestExa_AddressBook::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TestExa_AddressBook::~TestExa_AddressBook() {
  // @@protoc_insertion_point(destructor:GameMsg.TestExa.AddressBook)
  SharedDtor(*this);
}
inline void TestExa_AddressBook::SharedDtor(MessageLite& self) {
  TestExa_AddressBook& this_ = static_cast<TestExa_AddressBook&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* TestExa_AddressBook::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TestExa_AddressBook(arena);
}
constexpr auto TestExa_AddressBook::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TestExa_AddressBook, _impl_.person_) +
          decltype(TestExa_AddressBook::_impl_.person_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(TestExa_AddressBook, _impl_.person1_) +
          decltype(TestExa_AddressBook::_impl_.person1_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(TestExa_AddressBook), alignof(TestExa_AddressBook), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TestExa_AddressBook::PlacementNew_,
                                 sizeof(TestExa_AddressBook),
                                 alignof(TestExa_AddressBook));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TestExa_AddressBook::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TestExa_AddressBook_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TestExa_AddressBook::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TestExa_AddressBook>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TestExa_AddressBook::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TestExa_AddressBook>(), &TestExa_AddressBook::ByteSizeLong,
            &TestExa_AddressBook::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TestExa_AddressBook, _impl_._cached_size_),
        false,
    },
    &TestExa_AddressBook::kDescriptorMethods,
    &descriptor_table_messages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TestExa_AddressBook::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> TestExa_AddressBook::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameMsg::TestExa_AddressBook>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .GameMsg.TestExa.Person person1 = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(TestExa_AddressBook, _impl_.person1_)}},
    // repeated .GameMsg.TestExa.Person person = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TestExa_AddressBook, _impl_.person_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .GameMsg.TestExa.Person person = 1;
    {PROTOBUF_FIELD_OFFSET(TestExa_AddressBook, _impl_.person_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .GameMsg.TestExa.Person person1 = 2;
    {PROTOBUF_FIELD_OFFSET(TestExa_AddressBook, _impl_.person1_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GameMsg::TestExa_Person>()},
    {::_pbi::TcParser::GetTable<::GameMsg::TestExa_Person>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void TestExa_AddressBook::Clear() {
// @@protoc_insertion_point(message_clear_start:GameMsg.TestExa.AddressBook)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.person_.Clear();
  _impl_.person1_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TestExa_AddressBook::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TestExa_AddressBook& this_ = static_cast<const TestExa_AddressBook&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TestExa_AddressBook::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TestExa_AddressBook& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameMsg.TestExa.AddressBook)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .GameMsg.TestExa.Person person = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_person_size());
               i < n; i++) {
            const auto& repfield = this_._internal_person().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .GameMsg.TestExa.Person person1 = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_person1_size());
               i < n; i++) {
            const auto& repfield = this_._internal_person1().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameMsg.TestExa.AddressBook)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TestExa_AddressBook::ByteSizeLong(const MessageLite& base) {
          const TestExa_AddressBook& this_ = static_cast<const TestExa_AddressBook&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TestExa_AddressBook::ByteSizeLong() const {
          const TestExa_AddressBook& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameMsg.TestExa.AddressBook)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .GameMsg.TestExa.Person person = 1;
            {
              total_size += 1UL * this_._internal_person_size();
              for (const auto& msg : this_._internal_person()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .GameMsg.TestExa.Person person1 = 2;
            {
              total_size += 1UL * this_._internal_person1_size();
              for (const auto& msg : this_._internal_person1()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TestExa_AddressBook::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TestExa_AddressBook*>(&to_msg);
  auto& from = static_cast<const TestExa_AddressBook&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameMsg.TestExa.AddressBook)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_person()->MergeFrom(
      from._internal_person());
  _this->_internal_mutable_person1()->MergeFrom(
      from._internal_person1());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TestExa_AddressBook::CopyFrom(const TestExa_AddressBook& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameMsg.TestExa.AddressBook)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestExa_AddressBook::InternalSwap(TestExa_AddressBook* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.person_.InternalSwap(&other->_impl_.person_);
  _impl_.person1_.InternalSwap(&other->_impl_.person1_);
}

::google::protobuf::Metadata TestExa_AddressBook::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TestExa::_Internal {
 public:
};

TestExa::TestExa(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:GameMsg.TestExa)
}
TestExa::TestExa(
    ::google::protobuf::Arena* arena,
    const TestExa& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TestExa* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:GameMsg.TestExa)
}

inline void* TestExa::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TestExa(arena);
}
constexpr auto TestExa::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TestExa),
                                            alignof(TestExa));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TestExa::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TestExa_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TestExa::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<TestExa>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TestExa::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<TestExa>(), &TestExa::ByteSizeLong,
            &TestExa::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TestExa, _impl_._cached_size_),
        false,
    },
    &TestExa::kDescriptorMethods,
    &descriptor_table_messages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TestExa::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> TestExa::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameMsg::TestExa>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata TestExa::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GameMsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_messages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
